<?php

use \Console\Migration\BaseMigration;

class AddBookingPatientTable extends BaseMigration
{
    public function change()
    {
        $this->query("          
            CREATE TABLE IF NOT EXISTS `booking_patient` (
                `id` int(11) NOT NULL AUTO_INCREMENT,
                `organization_id` int(11) NOT NULL,
                `language_id` int(11) DEFAULT NULL,
                `title` tinyint(4) DEFAULT NULL,
                `first_name` varchar(255) NOT NULL,
                `middle_name` varchar(255) DEFAULT NULL,
                `parents_name` varchar(255) DEFAULT NULL,
                `last_name` varchar(255) NOT NULL,
                `suffix` tinyint(4) DEFAULT NULL,
                `ssn` varchar(40) DEFAULT NULL,
                `dob` date DEFAULT NULL,
                `gender` tinyint(4) DEFAULT NULL,
                `race` tinyint(4) DEFAULT NULL,
                `ethnicity` tinyint(4) DEFAULT NULL,
                `status_marital` tinyint(4) DEFAULT NULL,
                `status_employment` tinyint(4) DEFAULT NULL,
                `employer` varchar(255) DEFAULT NULL,
                `home_address` varchar(255) DEFAULT NULL,
                `home_apt_number` varchar(255) DEFAULT NULL,
                `home_state_id` int(11) DEFAULT NULL,
                `custom_home_state` varchar(255) DEFAULT NULL,
                `home_city_id` int(11) DEFAULT NULL,
                `custom_home_city` varchar(255) DEFAULT NULL,
                `home_zip_code` varchar(20) DEFAULT NULL,
                `home_country_id` int(11) DEFAULT NULL,
                `home_phone` varchar(40) DEFAULT NULL,
                `home_email` varchar(255) DEFAULT NULL,
                `ec_name` varchar(255) DEFAULT NULL,
                `ec_relationship` varchar(255) DEFAULT NULL,
                `ec_phone_number` varchar(255) DEFAULT NULL,
                `additional_phone` varchar(40) DEFAULT NULL,
                `employer_phone` varchar(40) DEFAULT NULL,
                `photo_id` int(11) DEFAULT NULL,
                `coverage_type_custom` varchar(255) DEFAULT NULL,
                `effective_date` varchar(255) DEFAULT NULL,
                `term_date` varchar(255) DEFAULT NULL,
                `renewal_date` varchar(255) DEFAULT NULL,
                `individual_out_of_pocket_maximum` varchar(255) DEFAULT NULL,
                `is_oon_benefits_cap` tinyint(4) DEFAULT '0',
                `oon_benefits_cap` varchar(255) DEFAULT NULL,
                `is_asc_benefits_cap` tinyint(4) DEFAULT '0',
                `asc_benefits_cap` varchar(255) DEFAULT NULL,
                `is_pre_existing_clauses` tinyint(4) DEFAULT '0',
                `pre_existing_clauses` varchar(255) DEFAULT NULL,
                `body_part` varchar(255) DEFAULT NULL,
                `is_clauses_pertaining` tinyint(4) DEFAULT '0',
                `subscribers_name` varchar(255) DEFAULT NULL,
                `authorization_number` varchar(255) DEFAULT NULL,
                `expiration` varchar(255) DEFAULT NULL,
                `spoke_with` varchar(255) DEFAULT NULL,
                `reference_number` varchar(255) DEFAULT NULL,
                `staff_member_name` varchar(255) DEFAULT NULL,
                `date` varchar(255) DEFAULT NULL,
                `oon_benefits` tinyint(4) DEFAULT '0',
                `pre_certification_required` tinyint(4) DEFAULT '0',
                `pre_certification_obtained` tinyint(4) DEFAULT '0',
                `self_funded` tinyint(4) DEFAULT '0',
                `co_pay` decimal(10,2) DEFAULT NULL,
                `co_insurance` decimal(10,2) DEFAULT NULL,
                `patients_responsibility` decimal(10,2) DEFAULT NULL,
                `individual_deductible` decimal(10,2) DEFAULT NULL,
                `individual_met_to_date` decimal(10,2) DEFAULT NULL,
                `family_deductible` decimal(10,2) DEFAULT NULL,
                `family_met_to_date` decimal(10,2) DEFAULT NULL,
                `yearly_maximum` varchar(255) DEFAULT NULL,
                `lifetime_maximum` varchar(255) DEFAULT NULL,
                `oon_reimbursement` tinyint(4) DEFAULT NULL,
                `individual_remaining_1` decimal(10,2) DEFAULT NULL,
                `individual_remaining_2` decimal(10,2) DEFAULT NULL,
                `family_remaining_1` decimal(10,2) DEFAULT NULL,
                `family_remaining_2` decimal(10,2) DEFAULT NULL,
                `family_out_of_pocket_maximum` varchar(255) DEFAULT NULL,
                `status` tinyint(1) DEFAULT '1',
                `insurance_verified` tinyint(1) DEFAULT '0',
                `is_pre_authorization_completed` tinyint(1) DEFAULT '0',
                `coverage_type` int(11) DEFAULT '0',
                `home_phone_type` tinyint(4) DEFAULT NULL,
                `additional_phone_type` tinyint(4) DEFAULT NULL,
                `ec_phone_type` tinyint(4) DEFAULT NULL,
                `relationship` tinyint(4) DEFAULT NULL,
                PRIMARY KEY (`id`)
            ) ENGINE=InnoDB;
            
            ALTER TABLE `booking_sheet` ADD COLUMN `booking_patient_id` int(11) NULL DEFAULT NULL AFTER `patient_id`;
        ");
    }
}
